import { Tutorial, ModuleCollection } from './types';

// WAF Basics Module
const wafBasicsTutorials: Tutorial[] = [
  {
    id: 'waf-top-5-issues',
    title: 'WAF: Top 5 Common Issues',
    author: 'Cloudflare Security Team',
    videoUrl: 'https://customer-education.cloudflare.com/waf-top-5',
    videoPoster: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=1200&h=600&fit=crop',
    description: 'Learn to identify and resolve the five most common WAF configuration issues that affect site security and performance.',
    totalTime: '12 minutes',
    prepTime: '3 minutes',
    cookTime: '9 minutes',
    difficulty: 'Easy',
    overview: 'The Web Application Firewall (WAF) is your first line of defense against malicious traffic. Understanding common configuration issues helps you maintain optimal security without blocking legitimate users. This tutorial covers the most frequent problems customers encounter and how to fix them quickly.',
    yield: 'Properly configured WAF',
    moduleId: 'waf-basics',
    featured: true,
    updatedDate: 'Jan. 15, 2026',
    ingredients: [
      { id: 'waf-ing-1', name: 'Cloudflare Account', description: 'With WAF access (Pro plan or higher)', required: true },
      { id: 'waf-ing-2', name: 'Active Domain', description: 'Domain proxied through Cloudflare', required: true },
      { id: 'waf-ing-3', name: 'Dashboard Access', description: 'Admin or Super Admin role', required: true },
      { id: 'waf-ing-4', name: 'Security Events Access', description: 'Ability to view firewall logs', required: false },
    ],
    steps: [
      { id: 'waf-step-1', number: 1, title: 'Identify False Positives', timestamp: '0:45', image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=500&fit=crop', description: 'Navigate to Security > Events in your Cloudflare dashboard. Look for legitimate requests being blocked by managed rules. Check the Ray ID, user agent, and request path to confirm these are false positives. Use filters to narrow down specific rule IDs causing issues.' },
      { id: 'waf-step-2', number: 2, title: 'Create Exception Rules', timestamp: '2:30', image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=500&fit=crop', description: 'Go to Security > WAF > Managed rules. Click "Add exception" to bypass specific rules for certain conditions. Use field matching like hostname, URI path, or IP address to create precise exceptions that don\'t compromise security.' },
      { id: 'waf-step-3', number: 3, title: 'Review Rate Limiting Configuration', timestamp: '4:15', image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=500&fit=crop', description: 'Check Security > WAF > Rate limiting rules. Ensure thresholds are appropriate for your traffic patterns. Common issue: setting limits too low causes legitimate users to be blocked during traffic spikes. Adjust counting expressions and mitigation actions as needed.' },
      { id: 'waf-step-4', number: 4, title: 'Verify Custom Rule Order', timestamp: '6:20', image: 'https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=800&h=500&fit=crop', description: 'Custom rules execute in order from top to bottom. Review Security > WAF > Custom rules and ensure allow rules come before block rules. Drag and drop to reorder. A common mistake is placing a broad block rule before specific allow rules.' },
      { id: 'waf-step-5', number: 5, title: 'Test and Monitor', timestamp: '8:45', image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=500&fit=crop', description: 'After making changes, monitor Security Events for 24-48 hours. Use the Activity log to track rule modifications. Set up notifications for high volumes of blocked requests. Gradually tune rules based on real traffic patterns rather than assumptions.' },
    ],
    rating: 4.9,
    ratingCount: 2847,
    comments: [
      { id: 'waf-c1', author: 'Marcus Chen', date: '2026-01-10', rating: 5, text: 'This saved us hours of troubleshooting! The false positive section was exactly what we needed.', helpful: 156 },
      { id: 'waf-c2', author: 'Sarah Johnson', date: '2026-01-08', rating: 5, text: 'Clear explanations and practical examples. Finally understand WAF rule ordering!', helpful: 98 },
    ],
  },
  {
    id: 'waf-troubleshooting-flowchart',
    title: 'WAF Troubleshooting Flowchart',
    author: 'Cloudflare Security Team',
    videoUrl: 'https://customer-education.cloudflare.com/waf-flowchart',
    videoPoster: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&h=600&fit=crop',
    description: 'Follow a systematic approach to diagnose and resolve WAF issues using our comprehensive troubleshooting flowchart.',
    totalTime: '15 minutes',
    prepTime: '5 minutes',
    cookTime: '10 minutes',
    difficulty: 'Easy',
    overview: 'When WAF issues arise, a systematic troubleshooting approach saves time and prevents security gaps. This flowchart-based tutorial guides you through diagnostic steps to quickly identify whether issues stem from managed rules, custom rules, rate limiting, or configuration errors.',
    yield: 'Resolved WAF issues',
    moduleId: 'waf-basics',
    ingredients: [
      { id: 'waf-flow-1', name: 'Ray ID from blocked request', description: 'Found in error page or logs', required: true },
      { id: 'waf-flow-2', name: 'Security Events access', description: 'To view firewall activity', required: true },
      { id: 'waf-flow-3', name: 'WAF configuration access', description: 'To make rule adjustments', required: true },
    ],
    steps: [
      { id: 'waf-flow-step-1', number: 1, title: 'Locate the Blocked Request', timestamp: '0:30', description: 'Use the Ray ID to find the specific request in Security > Events. Note the action taken (block, challenge, managed_challenge), the rule that triggered, and the request details including path, method, and headers.' },
      { id: 'waf-flow-step-2', number: 2, title: 'Determine Rule Type', timestamp: '2:15', description: 'Identify if the block came from: Managed Rules (OWASP, Cloudflare Managed Ruleset), Custom Rules (your organization created), Rate Limiting, or IP Access Rules. Each type requires different troubleshooting approaches.' },
      { id: 'waf-flow-step-3', number: 3, title: 'Assess Legitimacy', timestamp: '4:45', description: 'Evaluate if the block was correct. Check: Is the request from a known user/system? Does the payload contain suspicious patterns? Is the rate unusually high? If legitimate, proceed to create exceptions. If malicious, rules are working correctly.' },
      { id: 'waf-flow-step-4', number: 4, title: 'Apply Appropriate Fix', timestamp: '7:20', description: 'For false positives: Create WAF exceptions, adjust sensitivity levels, or modify custom rules. For rate limiting: Increase thresholds or add IP allowlists. For legitimate blocks: No action needed, but consider logging for compliance.' },
      { id: 'waf-flow-step-5', number: 5, title: 'Validate Resolution', timestamp: '10:30', description: 'Test the previously blocked request. Monitor Security Events for 1-2 hours to ensure the fix works without creating new issues. Document the change in your runbook for future reference.' },
    ],
    rating: 4.8,
    ratingCount: 1923,
    comments: [
      { id: 'waf-flow-c1', author: 'David Park', date: '2026-01-12', rating: 5, text: 'The flowchart approach makes troubleshooting so much faster. Great resource for our NOC team.', helpful: 87 },
    ],
  },
  {
    id: 'ui-tour',
    title: 'Cloudflare Dashboard UI Tour',
    author: 'Cloudflare Product Team',
    videoUrl: 'https://customer-education.cloudflare.com/ui-tour',
    videoPoster: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&h=600&fit=crop',
    description: 'Get familiar with the Cloudflare dashboard interface and learn where to find key features and settings.',
    totalTime: '10 minutes',
    difficulty: 'Easy',
    overview: 'The Cloudflare dashboard is your control center for managing security, performance, and reliability. This tour introduces the navigation structure, key sections, and how to quickly access the features you need most.',
    yield: 'Dashboard proficiency',
    moduleId: 'waf-basics',
    ingredients: [
      { id: 'ui-ing-1', name: 'Cloudflare Account', description: 'Any plan level', required: true },
      { id: 'ui-ing-2', name: 'At least one domain', description: 'Added to your account', required: true },
    ],
    steps: [
      { id: 'ui-step-1', number: 1, title: 'Navigate Account Home', timestamp: '0:25', description: 'From dash.cloudflare.com, explore the account home showing all your domains. Use the search bar to quickly find specific zones. Notice the account-level navigation on the left for global settings like billing and team members.' },
      { id: 'ui-step-2', number: 2, title: 'Explore Zone Dashboard', timestamp: '2:40', description: 'Click into a domain to see the zone dashboard. The left sidebar organizes features by category: Analytics, Security, Performance, Traffic, etc. The Overview tab provides quick insights into traffic and security events.' },
      { id: 'ui-step-3', number: 3, title: 'Use Quick Actions', timestamp: '5:15', description: 'Notice the quick actions bar at the top for common tasks. Access your profile, switch accounts, view notifications, and get help. The "?" icon provides contextual documentation for the current page.' },
      { id: 'ui-step-4', number: 4, title: 'Customize Your View', timestamp: '7:30', description: 'Bookmark frequently used pages. Use browser tabs to work on multiple zones simultaneously. Enable dark mode in your profile settings if preferred. Set up email notifications for important events.' },
    ],
    rating: 4.7,
    ratingCount: 3421,
    comments: [],
  },
  {
    id: 'api-shield-tokens',
    title: 'API Shield & API Tokens',
    author: 'Cloudflare API Team',
    videoUrl: 'https://customer-education.cloudflare.com/api-tokens',
    videoPoster: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=1200&h=600&fit=crop',
    description: 'Secure your APIs with API Shield and learn to create scoped API tokens for programmatic access to Cloudflare.',
    totalTime: '18 minutes',
    prepTime: '5 minutes',
    cookTime: '13 minutes',
    difficulty: 'Intermediate',
    overview: 'API security is critical for modern applications. Learn how to protect your APIs with Cloudflare API Shield features including schema validation, JWT validation, and mTLS. Plus, create secure API tokens for automation and integrations.',
    yield: 'Secured API endpoints',
    moduleId: 'waf-basics',
    ingredients: [
      { id: 'api-ing-1', name: 'Cloudflare Account', description: 'Enterprise plan for full API Shield', required: true },
      { id: 'api-ing-2', name: 'API endpoints', description: 'Hosted behind Cloudflare', required: true },
      { id: 'api-ing-3', name: 'OpenAPI schema', description: 'For schema validation (optional)', required: false },
    ],
    steps: [
      { id: 'api-step-1', number: 1, title: 'Enable API Shield', timestamp: '0:50', description: 'Navigate to Security > API Shield. Review your API endpoints discovered by Cloudflare. Enable endpoint management to see all API traffic patterns and identify shadow APIs.' },
      { id: 'api-step-2', number: 2, title: 'Configure Schema Validation', timestamp: '3:20', description: 'Upload your OpenAPI 3.0 schema. Enable schema validation to block requests that don\'t match your API specification. This prevents malformed requests and potential exploits.' },
      { id: 'api-step-3', number: 3, title: 'Set Up JWT Validation', timestamp: '6:45', description: 'Configure JWT validation rules if your API uses JSON Web Tokens. Specify the issuer, audience, and public keys. Cloudflare validates tokens at the edge before requests reach your origin.' },
      { id: 'api-step-4', number: 4, title: 'Create API Token', timestamp: '10:15', description: 'Go to My Profile > API Tokens > Create Token. Choose a template or create custom token. Select specific permissions (Zone.WAF:Edit, Zone.DNS:Read, etc.) and scope to specific zones. Set expiration date for security.' },
      { id: 'api-step-5', number: 5, title: 'Test API Token', timestamp: '14:30', description: 'Use the token in your API client or script. Test with curl: curl -X GET "https://api.cloudflare.com/client/v4/zones" -H "Authorization: Bearer YOUR_TOKEN". Verify permissions work as expected.' },
    ],
    rating: 4.8,
    ratingCount: 1567,
    comments: [
      { id: 'api-c1', author: 'Jennifer Liu', date: '2026-01-09', rating: 5, text: 'Schema validation caught several bugs in our mobile app before they hit production. Invaluable!', helpful: 134 },
    ],
  },
];

// Zero Trust Module
const zeroTrustTutorials: Tutorial[] = [
  {
    id: 'vpn-migration',
    title: 'VPN to Zero Trust Migration',
    author: 'Cloudflare Zero Trust Team',
    videoUrl: 'https://cloudflare.tv/vpn-migration',
    videoPoster: 'https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?w=1200&h=600&fit=crop',
    description: 'Migrate from traditional VPN to Cloudflare Zero Trust for better security, performance, and user experience.',
    totalTime: '35 minutes',
    prepTime: '15 minutes',
    cookTime: '20 minutes',
    difficulty: 'Intermediate',
    overview: 'Traditional VPNs create security bottlenecks and poor user experiences. Cloudflare Zero Trust provides secure access to applications without the drawbacks of legacy VPNs. This tutorial guides you through planning and executing a smooth migration.',
    yield: 'Zero Trust deployment',
    moduleId: 'zero-trust',
    ingredients: [
      { id: 'zt-ing-1', name: 'Cloudflare Zero Trust account', description: 'Free or paid plan', required: true },
      { id: 'zt-ing-2', name: 'Identity provider', description: 'Okta, Azure AD, Google, etc.', required: true },
      { id: 'zt-ing-3', name: 'Application inventory', description: 'List of internal apps to protect', required: true },
      { id: 'zt-ing-4', name: 'User directory', description: 'For access policies', required: true },
    ],
    steps: [
      { id: 'zt-step-1', number: 1, title: 'Assess Current VPN Usage', timestamp: '1:00', description: 'Document all applications accessed via VPN. Identify user groups and their access requirements. Note any compliance requirements. Create a prioritized migration list starting with low-risk applications.' },
      { id: 'zt-step-2', number: 2, title: 'Configure Identity Integration', timestamp: '5:30', description: 'In Zero Trust dashboard, go to Settings > Authentication. Add your identity provider (IdP). Configure SAML or OIDC integration. Test authentication with a pilot user group. Map IdP groups to Cloudflare Access groups.' },
      { id: 'zt-step-3', number: 3, title: 'Create Access Applications', timestamp: '11:45', description: 'Navigate to Access > Applications > Add an application. Choose self-hosted for internal apps. Enter application domain and subdomain. Configure session duration and authentication methods. Add CORS settings if needed for SPAs.' },
      { id: 'zt-step-4', number: 4, title: 'Define Access Policies', timestamp: '17:20', description: 'For each application, create policies determining who can access. Use identity-based rules (email, group membership), device posture checks, and geographic restrictions. Start with allow policies for pilot users, then expand.' },
      { id: 'zt-step-5', number: 5, title: 'Deploy WARP Client', timestamp: '23:10', description: 'Roll out Cloudflare WARP client to user devices. Configure device enrollment rules. Set up split tunneling to route only necessary traffic through Cloudflare. Enable device posture checks for additional security.' },
      { id: 'zt-step-6', number: 6, title: 'Migrate Users Gradually', timestamp: '28:40', description: 'Start with pilot group accessing non-critical apps. Gather feedback and adjust policies. Gradually migrate user groups and applications. Keep VPN running in parallel initially. Monitor Access logs for issues. Complete migration once confident.' },
    ],
    rating: 4.9,
    ratingCount: 2156,
    comments: [
      { id: 'zt-c1', author: 'Robert Martinez', date: '2026-01-11', rating: 5, text: 'Migrated 500 users off VPN in 3 weeks. Performance improved dramatically and users are much happier.', helpful: 203 },
    ],
  },
  {
    id: 'zero-trust-demo',
    title: 'Zero Trust Platform Demo',
    author: 'Cloudflare Zero Trust Team',
    videoUrl: 'https://cloudflare.tv/zt-demo',
    videoPoster: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=1200&h=600&fit=crop',
    description: 'Watch a comprehensive demo of Cloudflare Zero Trust capabilities including Access, Gateway, and Browser Isolation.',
    totalTime: '25 minutes',
    difficulty: 'Easy',
    overview: 'See Zero Trust in action with a guided demo covering the core features: secure application access, DNS and HTTP filtering, remote browser isolation, and data loss prevention. Perfect for understanding the platform before implementation.',
    yield: 'Zero Trust understanding',
    moduleId: 'zero-trust',
    ingredients: [
      { id: 'zt-demo-1', name: 'Cloudflare account', description: 'To follow along', required: false },
    ],
    steps: [
      { id: 'zt-demo-step-1', number: 1, title: 'Explore Access Features', timestamp: '1:15', description: 'See how Access protects internal applications with identity-based policies. Watch authentication flows with different IdPs. Observe how policies enforce least-privilege access based on user attributes and device posture.' },
      { id: 'zt-demo-step-2', number: 2, title: 'Review Gateway Capabilities', timestamp: '7:30', description: 'Learn how Gateway filters DNS and HTTP traffic to block threats and enforce acceptable use policies. See DNS filtering prevent malware callbacks. Watch HTTP filtering inspect encrypted traffic for data loss prevention.' },
      { id: 'zt-demo-step-3', number: 3, title: 'See Browser Isolation', timestamp: '14:20', description: 'Understand how remote browser isolation protects against browser-based threats. Watch risky websites load in isolated browsers. See how users browse normally while threats are contained in the cloud.' },
      { id: 'zt-demo-step-4', number: 4, title: 'Understand Analytics', timestamp: '19:45', description: 'Explore Zero Trust analytics and logs. See user activity, blocked threats, and policy violations. Learn how to investigate security incidents using detailed logs and Ray IDs.' },
    ],
    rating: 4.7,
    ratingCount: 3892,
    comments: [],
  },
  {
    id: 'waf-layer-7',
    title: 'WAF Layer 7 DDoS Protection',
    author: 'Cloudflare Security Team',
    videoUrl: 'https://customer-education.cloudflare.com/waf-l7',
    videoPoster: 'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=1200&h=600&fit=crop',
    description: 'Protect your applications from sophisticated Layer 7 DDoS attacks using Cloudflare WAF managed rules.',
    totalTime: '20 minutes',
    prepTime: '5 minutes',
    cookTime: '15 minutes',
    difficulty: 'Intermediate',
    overview: 'Layer 7 DDoS attacks target application logic and can bypass traditional defenses. Learn how Cloudflare\'s managed rules automatically detect and mitigate these attacks while keeping your site online for legitimate users.',
    yield: 'L7 DDoS protection',
    moduleId: 'zero-trust',
    ingredients: [
      { id: 'l7-ing-1', name: 'Cloudflare account', description: 'Pro plan or higher', required: true },
      { id: 'l7-ing-2', name: 'Proxied domain', description: 'Orange-clouded in DNS', required: true },
    ],
    steps: [
      { id: 'l7-step-1', number: 1, title: 'Enable DDoS Managed Rules', timestamp: '0:40', description: 'Go to Security > DDoS. Review the HTTP DDoS Attack Protection managed ruleset. Enable automatic mitigation. Cloudflare analyzes traffic patterns and automatically deploys countermeasures during attacks.' },
      { id: 'l7-step-2', number: 2, title: 'Configure Sensitivity', timestamp: '4:25', description: 'Adjust sensitivity levels for different rule groups. Higher sensitivity catches more attacks but may increase false positives. Start with default "Medium" and adjust based on your traffic patterns and tolerance for false positives.' },
      { id: 'l7-step-3', number: 3, title: 'Set Up Rate Limiting', timestamp: '8:50', description: 'Create rate limiting rules as additional protection. Limit requests per IP, per session, or per API endpoint. Use counting expressions to target specific attack patterns. Set appropriate thresholds based on normal traffic.' },
      { id: 'l7-step-4', number: 4, title: 'Monitor and Respond', timestamp: '13:30', description: 'During an attack, monitor Security > Analytics for real-time data. Check which rules are triggering and what traffic is being mitigated. Use Security Events to analyze attack patterns. Adjust rules if needed, but usually automatic mitigation is sufficient.' },
    ],
    rating: 4.8,
    ratingCount: 1734,
    comments: [
      { id: 'l7-c1', author: 'Ahmed Hassan', date: '2026-01-07', rating: 5, text: 'Survived a 10Gbps Layer 7 attack without any downtime. The automatic mitigation is incredible.', helpful: 178 },
    ],
  },
];

// AI Engineer Module
const aiEngineerTutorials: Tutorial[] = [
  {
    id: 'intro-to-ai',
    title: 'Introduction to AI on Cloudflare',
    author: 'Cloudflare AI Team',
    videoUrl: 'https://www.youtube.com/watch?v=intro-ai',
    videoPoster: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=1200&h=600&fit=crop',
    description: 'Learn the fundamentals of artificial intelligence and how Cloudflare makes AI accessible at the edge.',
    totalTime: '15 minutes',
    difficulty: 'Easy',
    overview: 'Artificial intelligence is transforming applications, but running AI models traditionally requires expensive infrastructure. Cloudflare brings AI to the edge, making it fast, affordable, and globally distributed. Start your AI journey here.',
    yield: 'AI fundamentals knowledge',
    moduleId: 'ai-engineer',
    ingredients: [
      { id: 'ai-intro-1', name: 'Basic programming knowledge', description: 'JavaScript or Python', required: true },
      { id: 'ai-intro-2', name: 'Cloudflare account', description: 'Free tier works', required: true },
    ],
    steps: [
      { id: 'ai-intro-step-1', number: 1, title: 'Understand AI Concepts', timestamp: '0:35', description: 'Learn the difference between machine learning, deep learning, and AI. Understand what models are and how they make predictions. Explore common AI use cases: text generation, image classification, sentiment analysis, translation, and embeddings.' },
      { id: 'ai-intro-step-2', number: 2, title: 'Explore Cloudflare AI Platform', timestamp: '3:45', description: 'Cloudflare Workers AI runs models on Cloudflare\'s global network. Models execute close to users for low latency. No GPUs to manage or provision. Pay only for inference requests. Access 50+ pre-trained models including Llama, Stable Diffusion, and BERT.' },
      { id: 'ai-intro-step-3', number: 3, title: 'Review AI Gateway Benefits', timestamp: '7:20', description: 'AI Gateway sits between your app and AI providers (OpenAI, Anthropic, etc.). Get caching, rate limiting, analytics, and cost controls. Monitor AI usage across your organization. Cache responses to reduce costs and improve speed.' },
      { id: 'ai-intro-step-4', number: 4, title: 'Plan Your First AI Project', timestamp: '11:10', description: 'Identify a use case in your application: chatbot, content moderation, search, recommendations, etc. Choose appropriate models based on task requirements. Estimate costs and latency needs. Start with Workers AI for simplicity or AI Gateway for flexibility.' },
    ],
    rating: 4.9,
    ratingCount: 4521,
    comments: [
      { id: 'ai-intro-c1', author: 'Lisa Wang', date: '2026-01-13', rating: 5, text: 'Perfect introduction! Finally understand how to add AI to my apps without a PhD.', helpful: 267 },
    ],
  },
  {
    id: 'workers-ai-walkthrough',
    title: 'Workers AI Complete Walkthrough',
    author: 'Cloudflare AI Team',
    videoUrl: 'https://cloudflare.tv/workers-ai',
    videoPoster: 'https://images.unsplash.com/photo-1676277791608-ac52e1dfc8c5?w=1200&h=600&fit=crop',
    description: 'Build your first AI-powered application using Workers AI with step-by-step guidance.',
    totalTime: '30 minutes',
    prepTime: '10 minutes',
    cookTime: '20 minutes',
    difficulty: 'Intermediate',
    overview: 'Workers AI lets you run machine learning models on Cloudflare\'s network without managing infrastructure. This hands-on tutorial walks through building a complete AI application from scratch.',
    yield: 'Working AI application',
    moduleId: 'ai-engineer',
    ingredients: [
      { id: 'wai-ing-1', name: 'Cloudflare Workers account', description: 'Paid plan for AI access', required: true },
      { id: 'wai-ing-2', name: 'Wrangler CLI', description: 'Latest version installed', required: true },
      { id: 'wai-ing-3', name: 'Node.js', description: 'Version 16.13 or later', required: true },
      { id: 'wai-ing-4', name: 'Code editor', description: 'VS Code recommended', required: true },
    ],
    steps: [
      { id: 'wai-step-1', number: 1, title: 'Set Up Workers AI Project', timestamp: '1:20', description: 'Run: wrangler init my-ai-app. Choose "Fetch handler" template. Add AI binding to wrangler.toml: [ai] binding = "AI". Install types: npm install --save-dev @cloudflare/workers-types. Your Worker can now access AI models.' },
      { id: 'wai-step-2', number: 2, title: 'Choose and Test a Model', timestamp: '5:40', description: 'Browse available models at developers.cloudflare.com/workers-ai/models/. For text generation, try @cf/meta/llama-2-7b-chat-int8. For images, use @cf/stabilityai/stable-diffusion-xl-base-1.0. Test models in the playground before coding.' },
      { id: 'wai-step-3', number: 3, title: 'Write AI Worker Code', timestamp: '11:15', description: 'In src/index.ts, use env.AI.run() to execute models. Pass model name and inputs. For text: await env.AI.run("@cf/meta/llama-2-7b-chat-int8", {messages: [{role: "user", content: prompt}]}). Handle responses and errors appropriately.' },
      { id: 'wai-step-4', number: 4, title: 'Add Streaming Responses', timestamp: '18:30', description: 'For better UX, stream AI responses: const stream = await env.AI.run(model, {stream: true, ...}). Return Response with readable stream. Client receives tokens as they\'re generated instead of waiting for complete response.' },
      { id: 'wai-step-5', number: 5, title: 'Deploy and Test', timestamp: '23:45', description: 'Run: wrangler deploy. Your AI Worker is now live globally. Test with curl or Postman. Monitor invocations in Workers dashboard. Check AI usage and costs in Analytics. Scale automatically as traffic grows.' },
    ],
    rating: 4.8,
    ratingCount: 2934,
    comments: [
      { id: 'wai-c1', author: 'Carlos Ruiz', date: '2026-01-10', rating: 5, text: 'Built a chatbot in 30 minutes! The streaming responses make it feel instant.', helpful: 189 },
    ],
  },
  {
    id: 'ai-gateway-setup',
    title: 'AI Gateway Setup and Configuration',
    author: 'Cloudflare AI Team',
    videoUrl: 'https://customer-education.cloudflare.com/ai-gateway',
    videoPoster: 'https://images.unsplash.com/photo-1655393001768-d946c97d6fd1?w=1200&h=600&fit=crop',
    description: 'Set up AI Gateway to manage, monitor, and optimize your AI API usage across multiple providers.',
    totalTime: '22 minutes',
    prepTime: '7 minutes',
    cookTime: '15 minutes',
    difficulty: 'Easy',
    overview: 'AI Gateway provides a unified interface for all your AI providers. Get caching, rate limiting, request logging, and cost analytics. Control AI spending and improve performance without changing your application code.',
    yield: 'Configured AI Gateway',
    moduleId: 'ai-engineer',
    ingredients: [
      { id: 'aig-ing-1', name: 'Cloudflare account', description: 'Free tier available', required: true },
      { id: 'aig-ing-2', name: 'AI provider API keys', description: 'OpenAI, Anthropic, etc.', required: true },
      { id: 'aig-ing-3', name: 'Existing AI application', description: 'Or willingness to build one', required: true },
    ],
    steps: [
      { id: 'aig-step-1', number: 1, title: 'Create AI Gateway', timestamp: '0:55', description: 'In Cloudflare dashboard, go to AI > AI Gateway. Click "Create Gateway". Name your gateway (e.g., "production-ai"). Copy the gateway URL provided. This URL will proxy requests to AI providers.' },
      { id: 'aig-step-2', number: 2, title: 'Update Application Code', timestamp: '4:10', description: 'Replace your AI provider URL with the gateway URL. For OpenAI: change "https://api.openai.com/v1" to "https://gateway.ai.cloudflare.com/v1/{account_id}/{gateway_id}/openai". Keep your API key in headers. No other code changes needed.' },
      { id: 'aig-step-3', number: 3, title: 'Configure Caching', timestamp: '8:35', description: 'In gateway settings, enable caching for appropriate requests. Set TTL based on content freshness needs. Identical requests return cached responses instantly and free. Great for common queries or embeddings.' },
      { id: 'aig-step-4', number: 4, title: 'Set Up Rate Limiting', timestamp: '13:20', description: 'Add rate limits to control costs and prevent abuse. Limit by API key, user ID, or IP address. Set per-minute, per-hour, or per-day limits. Requests exceeding limits return 429 errors instead of incurring costs.' },
      { id: 'aig-step-5', number: 5, title: 'Monitor Usage and Costs', timestamp: '17:40', description: 'View real-time analytics in AI Gateway dashboard. See request counts, cache hit rates, costs per model, and latency metrics. Set up alerts for unusual spending. Export logs for detailed analysis.' },
    ],
    rating: 4.9,
    ratingCount: 2167,
    comments: [
      { id: 'aig-c1', author: 'Emma Thompson', date: '2026-01-09', rating: 5, text: 'Reduced our OpenAI costs by 60% with caching alone. The analytics are incredibly useful.', helpful: 245 },
    ],
  },
];

// Full Stack Module
const fullStackTutorials: Tutorial[] = [
  {
    id: 'git-deployment',
    title: 'Deploy with GitHub and GitLab Integration',
    author: 'Cloudflare Pages Team',
    videoUrl: 'https://www.youtube.com/watch?v=git-deploy',
    videoPoster: 'https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=1200&h=600&fit=crop',
    description: 'Set up automatic deployments from your Git repository to Cloudflare Pages with preview environments.',
    totalTime: '18 minutes',
    prepTime: '5 minutes',
    cookTime: '13 minutes',
    difficulty: 'Easy',
    overview: 'Modern deployment workflows should be automatic and reliable. Connect your GitHub or GitLab repository to Cloudflare Pages for instant deployments on every push, with preview URLs for pull requests.',
    yield: 'Automated deployment pipeline',
    moduleId: 'full-stack',
    ingredients: [
      { id: 'git-ing-1', name: 'GitHub or GitLab account', description: 'With repository access', required: true },
      { id: 'git-ing-2', name: 'Cloudflare account', description: 'Free tier works', required: true },
      { id: 'git-ing-3', name: 'Web project', description: 'Static site or framework app', required: true },
    ],
    steps: [
      { id: 'git-step-1', number: 1, title: 'Connect Git Provider', timestamp: '0:45', description: 'In Cloudflare dashboard, go to Workers & Pages > Create application > Pages > Connect to Git. Authorize Cloudflare to access your GitHub or GitLab account. Select which repositories Cloudflare can access (all or specific ones).' },
      { id: 'git-step-2', number: 2, title: 'Select Repository and Branch', timestamp: '3:20', description: 'Choose the repository containing your project. Select the production branch (usually "main" or "master"). Pages will deploy this branch to your production URL. Other branches create preview deployments.' },
      { id: 'git-step-3', number: 3, title: 'Configure Build Settings', timestamp: '6:10', description: 'Pages auto-detects framework (React, Vue, Next.js, etc.). Verify build command (e.g., "npm run build"). Confirm output directory (e.g., "build", "dist", "out"). Add environment variables if needed. Set Node.js version if required.' },
      { id: 'git-step-4', number: 4, title: 'Deploy and Verify', timestamp: '9:40', description: 'Click "Save and Deploy". Pages clones your repo, runs build, and deploys to global CDN. Watch build logs for errors. Once complete, visit the provided pages.dev URL. Verify your site works correctly.' },
      { id: 'git-step-5', number: 5, title: 'Test Preview Deployments', timestamp: '13:25', description: 'Create a new branch and push changes. Open a pull request. Pages automatically creates a preview deployment with unique URL. Comment on PR includes preview link. Test changes before merging. Merge PR to deploy to production.' },
    ],
    rating: 4.9,
    ratingCount: 3876,
    comments: [
      { id: 'git-c1', author: 'Tom Anderson', date: '2026-01-12', rating: 5, text: 'Preview deployments are a game changer for our team. No more "works on my machine" issues.', helpful: 312 },
    ],
  },
  {
    id: 'workers-kv-guide',
    title: 'Workers KV: Key-Value Storage Guide',
    author: 'Cloudflare Workers Team',
    videoUrl: 'https://www.youtube.com/watch?v=workers-kv',
    videoPoster: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=1200&h=600&fit=crop',
    description: 'Learn how Workers KV provides globally distributed, low-latency key-value storage for your edge applications.',
    totalTime: '25 minutes',
    prepTime: '8 minutes',
    cookTime: '17 minutes',
    difficulty: 'Intermediate',
    overview: 'Workers KV is a global, low-latency key-value data store accessible from Cloudflare Workers. Perfect for configuration data, user preferences, cached content, and any data that needs to be read frequently and written occasionally.',
    yield: 'Working KV implementation',
    moduleId: 'full-stack',
    ingredients: [
      { id: 'kv-ing-1', name: 'Cloudflare Workers account', description: 'Paid plan for production', required: true },
      { id: 'kv-ing-2', name: 'Wrangler CLI', description: 'Latest version', required: true },
      { id: 'kv-ing-3', name: 'Existing Worker', description: 'Or new Worker project', required: true },
    ],
    steps: [
      { id: 'kv-step-1', number: 1, title: 'Create KV Namespace', timestamp: '1:10', description: 'Run: wrangler kv:namespace create "MY_KV". This creates a production namespace. For development: wrangler kv:namespace create "MY_KV" --preview. Copy the namespace IDs provided. Add to wrangler.toml under [[kv_namespaces]].' },
      { id: 'kv-step-2', number: 2, title: 'Write Data to KV', timestamp: '5:30', description: 'In Worker code, use env.MY_KV.put(key, value) to store data. Values can be strings or use JSON.stringify() for objects. Optional parameters: expirationTtl (seconds), expiration (timestamp), metadata. Writes are eventually consistent globally.' },
      { id: 'kv-step-3', number: 3, title: 'Read Data from KV', timestamp: '10:45', description: 'Use env.MY_KV.get(key) to retrieve values. Returns null if key doesn\'t exist. For JSON: JSON.parse(await env.MY_KV.get(key)). Reads are strongly consistent within a region, eventually consistent globally. Cache hit rate is typically 95%+.' },
      { id: 'kv-step-4', number: 4, title: 'List and Delete Keys', timestamp: '16:20', description: 'List keys: env.MY_KV.list({prefix: "user_"}). Returns paginated results. Delete: env.MY_KV.delete(key). Bulk operations available via API. Use metadata to store additional info without fetching full values.' },
      { id: 'kv-step-5', number: 5, title: 'Optimize KV Usage', timestamp: '20:40', description: 'KV is optimized for reads (millions/sec) not writes. Use for data read frequently, written occasionally. Implement cache-aside pattern. Consider expiration for temporary data. Monitor usage in Workers dashboard. KV is billed per read/write/delete/list operation.' },
    ],
    rating: 4.7,
    ratingCount: 2543,
    comments: [
      { id: 'kv-c1', author: 'Nina Patel', date: '2026-01-08', rating: 5, text: 'Using KV for user sessions across our global app. Sub-10ms reads everywhere!', helpful: 167 },
    ],
  },
  {
    id: 'd1-database',
    title: 'D1: Cloudflare\'s SQL Database',
    author: 'Cloudflare D1 Team',
    videoUrl: 'https://www.youtube.com/watch?v=d1-sql',
    videoPoster: 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=1200&h=600&fit=crop',
    description: 'Build applications with D1, Cloudflare\'s serverless SQL database built on SQLite.',
    totalTime: '28 minutes',
    prepTime: '10 minutes',
    cookTime: '18 minutes',
    difficulty: 'Intermediate',
    overview: 'D1 is Cloudflare\'s serverless SQL database that runs on SQLite. Get the power of relational databases without managing servers. Query from Workers with low latency and automatic replication.',
    yield: 'D1 database application',
    moduleId: 'full-stack',
    ingredients: [
      { id: 'd1-ing-1', name: 'Cloudflare Workers account', description: 'D1 in open beta', required: true },
      { id: 'd1-ing-2', name: 'Wrangler CLI', description: 'Version 3.0 or later', required: true },
      { id: 'd1-ing-3', name: 'SQL knowledge', description: 'Basic SQLite syntax', required: true },
    ],
    steps: [
      { id: 'd1-step-1', number: 1, title: 'Create D1 Database', timestamp: '1:25', description: 'Run: wrangler d1 create my-database. Wrangler creates a new D1 database and outputs binding configuration. Add the binding to wrangler.toml under [[d1_databases]]. Your Worker can now query this database.' },
      { id: 'd1-step-2', number: 2, title: 'Initialize Schema', timestamp: '6:10', description: 'Create schema.sql with your table definitions. Use standard SQLite syntax. Run: wrangler d1 execute my-database --file=schema.sql. This creates tables in your database. For migrations, use tools like Drizzle ORM or write custom migration scripts.' },
      { id: 'd1-step-3', number: 3, title: 'Query from Worker', timestamp: '11:40', description: 'In Worker code: const result = await env.DB.prepare("SELECT * FROM users WHERE id = ?").bind(userId).first(). Use .all() for multiple rows, .first() for one row, .run() for INSERT/UPDATE/DELETE. Prepared statements prevent SQL injection.' },
      { id: 'd1-step-4', number: 4, title: 'Use Batch Operations', timestamp: '17:55', description: 'For multiple queries, use batching: await env.DB.batch([stmt1, stmt2, stmt3]). Executes in a transaction. All succeed or all fail. More efficient than individual queries. Great for related operations like creating user and profile.' },
      { id: 'd1-step-5', number: 5, title: 'Monitor and Optimize', timestamp: '22:30', description: 'View query performance in Workers dashboard. D1 automatically replicates data globally. Reads are fast from nearest location. Writes go to primary region. Use indexes for frequently queried columns. EXPLAIN QUERY PLAN to optimize complex queries.' },
    ],
    rating: 4.8,
    ratingCount: 1987,
    comments: [
      { id: 'd1-c1', author: 'James Kim', date: '2026-01-11', rating: 5, text: 'Finally, a real database at the edge! Migrated from external DB and latency dropped 80%.', helpful: 201 },
    ],
  },
];

// Analytics & Security Module
const analyticsSecurityTutorials: Tutorial[] = [
  {
    id: 'security-center',
    title: 'Security Center Dashboards',
    author: 'Cloudflare Security Team',
    videoUrl: 'https://www.youtube.com/watch?v=security-center',
    videoPoster: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=1200&h=600&fit=crop',
    description: 'Master the Security Center to get a unified view of your security posture across all Cloudflare services.',
    totalTime: '20 minutes',
    difficulty: 'Easy',
    overview: 'Security Center provides a single pane of glass for your entire security posture. See threats, vulnerabilities, and recommendations across WAF, DDoS, Bot Management, and more.',
    yield: 'Security visibility',
    moduleId: 'analytics-security',
    ingredients: [
      { id: 'sc-ing-1', name: 'Cloudflare account', description: 'Pro plan or higher', required: true },
      { id: 'sc-ing-2', name: 'Active domains', description: 'With security features enabled', required: true },
    ],
    steps: [
      { id: 'sc-step-1', number: 1, title: 'Navigate Security Center', timestamp: '0:50', description: 'Go to Security > Security Center in dashboard. View Security Score showing overall posture (0-100). Review Insights for detected issues and recommendations. Check Security Events for recent threats blocked.' },
      { id: 'sc-step-2', number: 2, title: 'Review Security Insights', timestamp: '4:30', description: 'Insights identify misconfigurations and vulnerabilities. Each insight shows severity, affected zones, and remediation steps. Common insights: exposed admin panels, weak SSL settings, missing security headers. Click "Review" to investigate and fix.' },
      { id: 'sc-step-3', number: 3, title: 'Analyze Threat Activity', timestamp: '9:15', description: 'View threat trends over time. See which attack types are most common. Identify targeted zones and endpoints. Compare current activity to historical baselines. Use filters to drill into specific threat categories.' },
      { id: 'sc-step-4', number: 4, title: 'Implement Recommendations', timestamp: '14:40', description: 'Security Center suggests improvements based on your configuration. Enable recommended features like Bot Management or Page Shield. Adjust WAF sensitivity levels. Configure rate limiting for vulnerable endpoints. Track progress as Security Score improves.' },
    ],
    rating: 4.7,
    ratingCount: 2341,
    comments: [],
  },
  {
    id: 'analytics-comparison',
    title: 'Web Analytics vs. Analytics Engine',
    author: 'Cloudflare Analytics Team',
    videoUrl: 'https://www.youtube.com/watch?v=analytics-comp',
    videoPoster: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&h=600&fit=crop',
    description: 'Understand the differences between Cloudflare Web Analytics and Analytics Engine to choose the right tool.',
    totalTime: '16 minutes',
    difficulty: 'Easy',
    overview: 'Cloudflare offers two analytics solutions: Web Analytics for website metrics and Analytics Engine for custom application data. Learn when to use each and how they complement each other.',
    yield: 'Analytics understanding',
    moduleId: 'analytics-security',
    ingredients: [
      { id: 'analytics-ing-1', name: 'Cloudflare account', description: 'Free tier available', required: true },
    ],
    steps: [
      { id: 'analytics-step-1', number: 1, title: 'Understand Web Analytics', timestamp: '0:40', description: 'Web Analytics tracks website visitors without cookies or tracking scripts. Privacy-first alternative to Google Analytics. Shows page views, visitors, referrers, countries, browsers, and devices. Lightweight beacon (< 2KB). Free for all customers. Add to any site, even non-Cloudflare.' },
      { id: 'analytics-step-2', number: 2, title: 'Explore Analytics Engine', timestamp: '4:20', description: 'Analytics Engine stores custom metrics from Workers. Write any data points you want to track. Query with SQL for flexible analysis. Perfect for API metrics, business KPIs, custom events. Billed per data point written and queried. Requires Workers Paid plan.' },
      { id: 'analytics-step-3', number: 3, title: 'Choose the Right Tool', timestamp: '8:35', description: 'Use Web Analytics for: website traffic, user behavior, marketing attribution. Use Analytics Engine for: API performance, business metrics, custom application data, A/B test results. Use both together for complete visibility into web and application performance.' },
      { id: 'analytics-step-4', number: 4, title: 'Set Up Your Analytics', timestamp: '11:50', description: 'For Web Analytics: Add beacon script to HTML or enable in Pages settings. For Analytics Engine: Create dataset with wrangler, write data from Workers using env.ANALYTICS.writeDataPoint(). Query data via API or GraphQL. Build dashboards with your favorite BI tool.' },
    ],
    rating: 4.6,
    ratingCount: 1876,
    comments: [],
  },
  {
    id: 'waf-event-logs',
    title: 'WAF Event Log Analysis',
    author: 'Cloudflare Security Team',
    videoUrl: 'https://www.youtube.com/watch?v=waf-logs',
    videoPoster: 'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=1200&h=600&fit=crop',
    description: 'Learn to analyze WAF security events to investigate incidents and optimize your security rules.',
    totalTime: '22 minutes',
    prepTime: '5 minutes',
    cookTime: '17 minutes',
    difficulty: 'Intermediate',
    overview: 'WAF Event Logs provide detailed information about every security event. Master log analysis to troubleshoot false positives, investigate attacks, and fine-tune your security configuration.',
    yield: 'Log analysis skills',
    moduleId: 'analytics-security',
    ingredients: [
      { id: 'waf-log-ing-1', name: 'Cloudflare account', description: 'Pro plan or higher', required: true },
      { id: 'waf-log-ing-2', name: 'Active WAF rules', description: 'Generating security events', required: true },
    ],
    steps: [
      { id: 'waf-log-step-1', number: 1, title: 'Access Security Events', timestamp: '0:55', description: 'Navigate to Security > Events. View real-time security events as they occur. Each event shows: timestamp, action taken, rule triggered, request details, Ray ID. Use time picker to view historical events (retention varies by plan).' },
      { id: 'waf-log-step-2', number: 2, title: 'Filter and Search Events', timestamp: '3:40', description: 'Use filters to narrow results: Action (block, challenge, log), Source (managed rules, custom rules, rate limiting), Host, Path, Country, IP. Combine filters for precise queries. Save common filter combinations for quick access. Export filtered results for offline analysis.' },
      { id: 'waf-log-step-3', number: 3, title: 'Investigate Individual Events', timestamp: '7:25', description: 'Click an event to see full details. Review request headers, cookies, query parameters. See which rule triggered and why. Check matched patterns or signatures. Use Ray ID to correlate with origin logs. Determine if event is legitimate block or false positive.' },
      { id: 'waf-log-step-4', number: 4, title: 'Identify Patterns and Trends', timestamp: '12:10', description: 'Look for patterns in blocked requests. Multiple blocks from same IP might indicate attack. Sudden spike in challenges could mean bot activity. Consistent false positives on specific endpoints need rule adjustments. Use Activity Log to see recent rule changes that might correlate with issues.' },
      { id: 'waf-log-step-5', number: 5, title: 'Take Action Based on Analysis', timestamp: '16:45', description: 'For false positives: Create WAF exceptions or adjust rule sensitivity. For attacks: Verify rules are working correctly, consider adding custom rules for specific patterns. For performance: Optimize rules to reduce unnecessary processing. Document findings and actions for team knowledge base.' },
    ],
    rating: 4.8,
    ratingCount: 2109,
    comments: [
      { id: 'waf-log-c1', author: 'Rachel Green', date: '2026-01-06', rating: 5, text: 'The filtering capabilities are excellent. Found and fixed a false positive affecting our API in minutes.', helpful: 143 },
    ],
  },
];

// Specialized Ops Module
const specializedOpsTutorials: Tutorial[] = [
  {
    id: 'docs-interaction',
    title: 'Effective Documentation Navigation',
    author: 'Cloudflare Docs Team',
    videoUrl: 'https://customer-education.cloudflare.com/docs-interaction',
    videoPoster: 'https://images.unsplash.com/photo-1456324504439-367cee3b3c32?w=1200&h=600&fit=crop',
    description: 'Learn to efficiently navigate and search Cloudflare documentation to find answers quickly.',
    totalTime: '12 minutes',
    difficulty: 'Easy',
    overview: 'Cloudflare documentation is comprehensive but can be overwhelming. Master search techniques, understand doc structure, and learn where to find specific information types.',
    yield: 'Documentation proficiency',
    moduleId: 'specialized-ops',
    ingredients: [
      { id: 'docs-ing-1', name: 'Internet access', description: 'To access developers.cloudflare.com', required: true },
    ],
    steps: [
      { id: 'docs-step-1', number: 1, title: 'Understand Doc Structure', timestamp: '0:30', description: 'Docs are organized by product (Workers, Pages, R2, etc.). Each product has: Get Started (quickstart guides), Configuration (detailed settings), Tutorials (step-by-step guides), API Reference (technical specs), Troubleshooting (common issues). Start with Get Started for new products.' },
      { id: 'docs-step-2', number: 2, title: 'Use Search Effectively', timestamp: '3:15', description: 'Search bar at top of docs. Use specific terms: "wrangler deploy error" not "deploy problem". Search includes code examples. Filter results by product if needed. Recent searches saved for quick access. Search also covers community forum and blog posts.' },
      { id: 'docs-step-3', number: 3, title: 'Navigate with Breadcrumbs', timestamp: '6:20', description: 'Breadcrumbs at top show your location in doc hierarchy. Click to jump to parent sections. Left sidebar shows full product doc tree. Right sidebar shows headings on current page for quick jumping. Use browser back button to return to previous pages.' },
      { id: 'docs-step-4', number: 4, title: 'Leverage Code Examples', timestamp: '9:10', description: 'Most guides include copy-paste code examples. Examples show multiple languages when applicable. Code snippets include comments explaining key parts. GitHub links provided for complete example projects. Try examples in your own environment to learn by doing.' },
    ],
    rating: 4.5,
    ratingCount: 1654,
    comments: [],
  },
  {
    id: 'ssl-origin',
    title: 'SSL/TLS Origin Configuration',
    author: 'Cloudflare SSL Team',
    videoUrl: 'https://customer-education.cloudflare.com/ssl-origin',
    videoPoster: 'https://images.unsplash.com/photo-1614064641938-3bbee52942c7?w=1200&h=600&fit=crop',
    description: 'Configure SSL/TLS between Cloudflare and your origin server for end-to-end encryption.',
    totalTime: '25 minutes',
    prepTime: '10 minutes',
    cookTime: '15 minutes',
    difficulty: 'Intermediate',
    overview: 'Proper SSL/TLS configuration ensures encrypted connections from visitors to Cloudflare AND from Cloudflare to your origin. Learn about SSL modes, origin certificates, and best practices for secure configurations.',
    yield: 'Secure SSL setup',
    moduleId: 'specialized-ops',
    ingredients: [
      { id: 'ssl-ing-1', name: 'Cloudflare account', description: 'Any plan level', required: true },
      { id: 'ssl-ing-2', name: 'Origin server', description: 'With SSL certificate capability', required: true },
      { id: 'ssl-ing-3', name: 'Server access', description: 'To install certificates', required: true },
    ],
    steps: [
      { id: 'ssl-step-1', number: 1, title: 'Understand SSL Modes', timestamp: '1:05', description: 'Go to SSL/TLS > Overview. Four modes available: Off (not recommended), Flexible (Cloudflare to visitor encrypted, Cloudflare to origin not), Full (encrypted both ways but origin cert can be self-signed), Full (strict) (encrypted both ways with valid origin cert). Choose Full (strict) for production.' },
      { id: 'ssl-step-2', number: 2, title: 'Generate Origin Certificate', timestamp: '5:20', description: 'Go to SSL/TLS > Origin Server > Create Certificate. Cloudflare generates free certificate valid for 15 years. Add hostnames to protect (*.example.com for wildcard). Choose key format (PEM recommended). Download certificate and private key.' },
      { id: 'ssl-step-3', number: 3, title: 'Install on Origin Server', timestamp: '10:45', description: 'Install certificate and private key on your web server. For Apache: add to VirtualHost config. For Nginx: add ssl_certificate and ssl_certificate_key directives. For other servers: consult server documentation. Restart web server to apply changes.' },
      { id: 'ssl-step-4', number: 4, title: 'Enable Full (Strict) Mode', timestamp: '16:30', description: 'Return to SSL/TLS > Overview. Select Full (strict) mode. This enforces valid certificates on origin. Test your site to ensure it loads correctly. Check for mixed content warnings (HTTP resources on HTTPS page). Fix any issues before proceeding.' },
      { id: 'ssl-step-5', number: 5, title: 'Configure Additional Settings', timestamp: '20:15', description: 'Enable Always Use HTTPS to redirect HTTP to HTTPS. Enable HSTS (HTTP Strict Transport Security) for additional security. Set Minimum TLS Version to 1.2 or higher. Enable TLS 1.3 for better performance. Configure Authenticated Origin Pulls for extra security.' },
    ],
    rating: 4.9,
    ratingCount: 2876,
    comments: [
      { id: 'ssl-c1', author: 'Michael Chen', date: '2026-01-09', rating: 5, text: 'Origin certificates are so easy! No more paying for SSL certs or dealing with Let\'s Encrypt renewals.', helpful: 234 },
    ],
  },
];

// Combine all tutorials
export const allTutorials: Tutorial[] = [
  ...wafBasicsTutorials,
  ...zeroTrustTutorials,
  ...aiEngineerTutorials,
  ...fullStackTutorials,
  ...analyticsSecurityTutorials,
  ...specializedOpsTutorials,
];

// Create module collections
export const allModuleCollections: ModuleCollection[] = [
  {
    id: 'waf-basics',
    title: 'WAF Basics',
    description: 'Master Web Application Firewall fundamentals, troubleshooting, and best practices for protecting your applications.',
    tutorials: wafBasicsTutorials,
  },
  {
    id: 'zero-trust',
    title: 'Zero Trust Security',
    description: 'Implement Zero Trust architecture with Cloudflare Access, Gateway, and advanced security features.',
    tutorials: zeroTrustTutorials,
  },
  {
    id: 'ai-engineer',
    title: 'AI Engineering',
    description: 'Build AI-powered applications with Workers AI and AI Gateway. Run models at the edge with low latency.',
    tutorials: aiEngineerTutorials,
  },
  {
    id: 'full-stack',
    title: 'Full Stack Development',
    description: 'Deploy modern web applications with Pages, Workers, and Cloudflare\'s storage solutions.',
    tutorials: fullStackTutorials,
  },
  {
    id: 'analytics-security',
    title: 'Analytics & Security',
    description: 'Monitor your security posture, analyze threats, and gain insights into your application performance.',
    tutorials: analyticsSecurityTutorials,
  },
  {
    id: 'specialized-ops',
    title: 'Specialized Operations',
    description: 'Advanced operational topics including SSL/TLS configuration and effective documentation usage.',
    tutorials: specializedOpsTutorials,
  },
];

export const featuredTutorial = allTutorials.find(t => t.featured) || allTutorials[0];
