import { Module } from './types';

export const modules: Module[] = [
  {
    id: 'workers-101',
    title: 'Getting Started with Cloudflare Workers',
    videoUrl: 'https://customer-rhnwzxvb3mg4wz3.cloudflarestream.com/d5d1b4f3f8e6f8e6f8e6f8e6f8e6f8e6/manifest/video.m3u8',
    videoPoster: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=1200&h=600&fit=crop',
    description: 'Learn how to deploy your first serverless function on Cloudflare Workers in minutes.',
    duration: '15 min',
    difficulty: 'Beginner',
    overview: 'Cloudflare Workers provides a serverless execution environment that allows you to create entirely new applications or augment existing ones without configuring or maintaining infrastructure. This tutorial will guide you through creating, testing, and deploying your first Worker.',
    ingredients: [
      {
        id: 'ing-1',
        name: 'Cloudflare Account',
        description: 'Free account with Workers enabled',
        required: true,
      },
      {
        id: 'ing-2',
        name: 'Node.js',
        description: 'Version 16.13.0 or later',
        required: true,
      },
      {
        id: 'ing-3',
        name: 'Wrangler CLI',
        description: 'Latest version installed globally',
        required: true,
      },
      {
        id: 'ing-4',
        name: 'Code Editor',
        description: 'VS Code or your preferred editor',
        required: false,
      },
    ],
    steps: [
      {
        id: 'step-1',
        number: 1,
        title: 'Install Wrangler CLI',
        description: 'Open your terminal and install Wrangler, the official Cloudflare Workers CLI tool. Run: npm install -g wrangler',
        tips: ['Make sure you have Node.js installed first', 'Use sudo on Mac/Linux if you encounter permission errors'],
      },
      {
        id: 'step-2',
        number: 2,
        title: 'Authenticate with Cloudflare',
        description: 'Log in to your Cloudflare account using Wrangler. Run: wrangler login. This will open a browser window for authentication.',
        tips: ['Keep the browser window open until authentication completes', 'You only need to do this once per machine'],
      },
      {
        id: 'step-3',
        number: 3,
        title: 'Create a New Worker Project',
        description: 'Initialize a new Worker project by running: wrangler init my-worker. Choose "Fetch handler" when prompted and select TypeScript for type safety.',
        tips: ['Use a descriptive project name', 'TypeScript provides better autocomplete and error checking'],
      },
      {
        id: 'step-4',
        number: 4,
        title: 'Write Your Worker Code',
        description: 'Open src/index.ts and replace the default code with your custom logic. The fetch handler receives incoming requests and returns responses.',
        tips: ['Start simple with a "Hello World" response', 'Use async/await for asynchronous operations', 'Test your logic locally before deploying'],
      },
      {
        id: 'step-5',
        number: 5,
        title: 'Test Locally',
        description: 'Run your Worker locally using: wrangler dev. This starts a local development server at http://localhost:8787.',
        tips: ['Hot reload is enabled by default', 'Check the console for any errors', 'Test different request methods and paths'],
      },
      {
        id: 'step-6',
        number: 6,
        title: 'Deploy to Production',
        description: 'When ready, deploy your Worker to Cloudflare\'s global network: wrangler deploy. Your Worker will be available at your-worker.your-subdomain.workers.dev.',
        tips: ['Review your wrangler.toml configuration first', 'Use environment variables for sensitive data', 'Monitor your Worker in the Cloudflare dashboard'],
      },
    ],
    rating: 4.8,
    ratingCount: 342,
    comments: [
      {
        id: 'comment-1',
        author: 'Sarah Chen',
        date: '2024-01-10',
        rating: 5,
        text: 'Excellent tutorial! I had my first Worker deployed in under 20 minutes. The step-by-step approach made it really easy to follow along.',
        helpful: 24,
      },
      {
        id: 'comment-2',
        author: 'Mike Rodriguez',
        date: '2024-01-08',
        rating: 4,
        text: 'Great introduction to Workers. Would love to see more advanced examples like KV storage integration.',
        helpful: 18,
      },
      {
        id: 'comment-3',
        author: 'Emma Thompson',
        date: '2024-01-05',
        rating: 5,
        text: 'Clear and concise. The tips for each step were particularly helpful for troubleshooting.',
        helpful: 15,
      },
    ],
  },
  {
    id: 'pages-deployment',
    title: 'Deploy a React App with Cloudflare Pages',
    videoUrl: 'https://customer-rhnwzxvb3mg4wz3.cloudflarestream.com/d5d1b4f3f8e6f8e6f8e6f8e6f8e6f8e6/manifest/video.m3u8',
    videoPoster: 'https://images.unsplash.com/photo-1618477388954-7852f32655ec?w=1200&h=600&fit=crop',
    description: 'Deploy your React application to Cloudflare Pages with automatic builds and global CDN distribution.',
    duration: '20 min',
    difficulty: 'Beginner',
    overview: 'Cloudflare Pages is a JAMstack platform for frontend developers to collaborate and deploy websites. Connect your Git repository and Pages will automatically build and deploy your site to Cloudflare\'s global network.',
    ingredients: [
      {
        id: 'ing-5',
        name: 'GitHub/GitLab Account',
        description: 'Repository with your React app',
        required: true,
      },
      {
        id: 'ing-6',
        name: 'Cloudflare Account',
        description: 'Free account with Pages enabled',
        required: true,
      },
      {
        id: 'ing-7',
        name: 'React Application',
        description: 'Working React app ready to deploy',
        required: true,
      },
    ],
    steps: [
      {
        id: 'step-7',
        number: 1,
        title: 'Connect Your Repository',
        description: 'In the Cloudflare dashboard, navigate to Pages and click "Create a project". Connect your GitHub or GitLab account and select your React repository.',
        tips: ['Grant only the necessary repository permissions', 'You can connect multiple repositories later'],
      },
      {
        id: 'step-8',
        number: 2,
        title: 'Configure Build Settings',
        description: 'Set the build command to "npm run build" and the output directory to "build" or "dist" depending on your setup. Pages will auto-detect React projects.',
        tips: ['Verify your package.json has the correct build script', 'Add environment variables if needed'],
      },
      {
        id: 'step-9',
        number: 3,
        title: 'Deploy and Monitor',
        description: 'Click "Save and Deploy". Pages will build your site and deploy it to a unique URL. Monitor the build logs for any errors.',
        tips: ['First builds may take a few minutes', 'Check build logs if deployment fails', 'Your site gets a preview URL immediately'],
      },
      {
        id: 'step-10',
        number: 4,
        title: 'Set Up Custom Domain',
        description: 'Add a custom domain in the Pages settings. Update your DNS records to point to Cloudflare. SSL certificates are automatically provisioned.',
        tips: ['DNS changes may take up to 24 hours', 'Use Cloudflare nameservers for best performance', 'HTTPS is enabled by default'],
      },
    ],
    rating: 4.9,
    ratingCount: 256,
    comments: [
      {
        id: 'comment-4',
        author: 'Alex Kumar',
        date: '2024-01-12',
        rating: 5,
        text: 'Deployed my portfolio site in minutes! The automatic builds from Git are a game changer.',
        helpful: 31,
      },
    ],
  },
  {
    id: 'r2-storage',
    title: 'Object Storage with Cloudflare R2',
    videoUrl: 'https://customer-rhnwzxvb3mg4wz3.cloudflarestream.com/d5d1b4f3f8e6f8e6f8e6f8e6f8e6f8e6/manifest/video.m3u8',
    videoPoster: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=1200&h=600&fit=crop',
    description: 'Store and retrieve objects using Cloudflare R2, an S3-compatible storage solution with zero egress fees.',
    duration: '25 min',
    difficulty: 'Intermediate',
    overview: 'Cloudflare R2 Storage allows developers to store large amounts of unstructured data without the costly egress bandwidth fees associated with typical cloud storage services. Learn how to create buckets, upload files, and integrate R2 with your applications.',
    ingredients: [
      {
        id: 'ing-8',
        name: 'Cloudflare Account',
        description: 'Account with R2 enabled',
        required: true,
      },
      {
        id: 'ing-9',
        name: 'AWS SDK or S3 Client',
        description: 'For programmatic access',
        required: true,
      },
      {
        id: 'ing-10',
        name: 'API Tokens',
        description: 'R2 access credentials',
        required: true,
      },
    ],
    steps: [
      {
        id: 'step-11',
        number: 1,
        title: 'Create an R2 Bucket',
        description: 'Navigate to R2 in your Cloudflare dashboard and create a new bucket. Choose a unique name and select your preferred location.',
        tips: ['Bucket names must be globally unique', 'Choose a location close to your users'],
      },
      {
        id: 'step-12',
        number: 2,
        title: 'Generate API Tokens',
        description: 'Create R2 API tokens with appropriate permissions. You\'ll need the Access Key ID and Secret Access Key for authentication.',
        tips: ['Store credentials securely', 'Use separate tokens for development and production', 'Limit token permissions to only what\'s needed'],
      },
      {
        id: 'step-13',
        number: 3,
        title: 'Configure Your Application',
        description: 'Install the AWS SDK and configure it to use R2 endpoints. Set the endpoint URL to your account\'s R2 endpoint.',
        tips: ['R2 is S3-compatible', 'Use environment variables for credentials', 'Test connection before uploading files'],
      },
      {
        id: 'step-14',
        number: 4,
        title: 'Upload and Retrieve Objects',
        description: 'Use the SDK to upload files to your bucket. Implement proper error handling and consider using multipart uploads for large files.',
        tips: ['Add metadata to objects for better organization', 'Implement retry logic for failed uploads', 'Use presigned URLs for temporary access'],
      },
    ],
    rating: 4.7,
    ratingCount: 189,
    comments: [
      {
        id: 'comment-5',
        author: 'Jordan Lee',
        date: '2024-01-09',
        rating: 5,
        text: 'Finally switched from S3 to R2. The zero egress fees are saving us thousands per month!',
        helpful: 42,
      },
      {
        id: 'comment-6',
        author: 'Priya Patel',
        date: '2024-01-07',
        rating: 4,
        text: 'Good tutorial. Would be helpful to include examples for different programming languages.',
        helpful: 12,
      },
    ],
  },
];
