import { Tutorial, ModuleCollection } from './types';

export const tutorials: Tutorial[] = [
  {
    id: 'workers-101',
    title: 'Getting Started with Cloudflare Workers',
    author: 'Sarah Chen',
    videoUrl: 'https://customer-rhnwzxvb3mg4wz3.cloudflarestream.com/d5d1b4f3f8e6f8e6f8e6f8e6f8e6f8e6/manifest/video.m3u8',
    videoPoster: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=1200&h=600&fit=crop',
    description: 'Learn how to deploy your first serverless function on Cloudflare Workers in minutes.',
    totalTime: '15 minutes',
    prepTime: '5 minutes',
    cookTime: '10 minutes',
    difficulty: 'Easy',
    overview: 'Cloudflare Workers provides a serverless execution environment that allows you to create entirely new applications or augment existing ones without configuring or maintaining infrastructure. This tutorial will guide you through creating, testing, and deploying your first Worker.',
    yield: '1 deployed Worker',
    moduleId: 'serverless-computing',
    featured: true,
    updatedDate: 'Feb. 26, 2025',
    ingredients: [
      {
        id: 'ing-1',
        name: 'Cloudflare Account',
        description: 'Free account with Workers enabled',
        required: true,
      },
      {
        id: 'ing-2',
        name: 'Node.js',
        description: 'Version 16.13.0 or later',
        required: true,
      },
      {
        id: 'ing-3',
        name: 'Wrangler CLI',
        description: 'Latest version installed globally',
        required: true,
      },
      {
        id: 'ing-4',
        name: 'Code Editor',
        description: 'VS Code or your preferred editor',
        required: false,
      },
    ],
    steps: [
      {
        id: 'step-1',
        number: 1,
        title: 'Install Wrangler CLI',
        description: 'Open your terminal and install Wrangler, the official Cloudflare Workers CLI tool. Run: npm install -g wrangler. Make sure you have Node.js installed first. Use sudo on Mac/Linux if you encounter permission errors.',
      },
      {
        id: 'step-2',
        number: 2,
        title: 'Authenticate with Cloudflare',
        description: 'Log in to your Cloudflare account using Wrangler. Run: wrangler login. This will open a browser window for authentication. Keep the browser window open until authentication completes. You only need to do this once per machine.',
      },
      {
        id: 'step-3',
        number: 3,
        title: 'Create a New Worker Project',
        description: 'Initialize a new Worker project by running: wrangler init my-worker. Choose "Fetch handler" when prompted and select TypeScript for type safety. Use a descriptive project name. TypeScript provides better autocomplete and error checking.',
      },
      {
        id: 'step-4',
        number: 4,
        title: 'Write Your Worker Code',
        description: 'Open src/index.ts and replace the default code with your custom logic. The fetch handler receives incoming requests and returns responses. Start simple with a "Hello World" response. Use async/await for asynchronous operations. Test your logic locally before deploying.',
      },
      {
        id: 'step-5',
        number: 5,
        title: 'Test Locally',
        description: 'Run your Worker locally using: wrangler dev. This starts a local development server at http://localhost:8787. Hot reload is enabled by default. Check the console for any errors. Test different request methods and paths.',
      },
      {
        id: 'step-6',
        number: 6,
        title: 'Deploy to Production',
        description: 'When ready, deploy your Worker to Cloudflare\'s global network: wrangler deploy. Your Worker will be available at your-worker.your-subdomain.workers.dev. Review your wrangler.toml configuration first. Use environment variables for sensitive data. Monitor your Worker in the Cloudflare dashboard.',
      },
    ],
    rating: 4.8,
    ratingCount: 1168,
    comments: [
      {
        id: 'comment-1',
        author: 'Sarah Chen',
        date: '2024-01-10',
        rating: 5,
        text: 'Excellent tutorial! I had my first Worker deployed in under 20 minutes. The step-by-step approach made it really easy to follow along.',
        helpful: 24,
      },
      {
        id: 'comment-2',
        author: 'Mike Rodriguez',
        date: '2024-01-08',
        rating: 4,
        text: 'Great introduction to Workers. Would love to see more advanced examples like KV storage integration.',
        helpful: 18,
      },
    ],
  },
  {
    id: 'pages-deployment',
    title: 'Deploy a React App with Cloudflare Pages',
    author: 'Naz Deravian',
    videoUrl: 'https://customer-rhnwzxvb3mg4wz3.cloudflarestream.com/d5d1b4f3f8e6f8e6f8e6f8e6f8e6f8e6/manifest/video.m3u8',
    videoPoster: 'https://images.unsplash.com/photo-1618477388954-7852f32655ec?w=1200&h=600&fit=crop',
    description: 'Deploy your React application to Cloudflare Pages with automatic builds and global CDN distribution.',
    totalTime: '20 minutes',
    prepTime: '10 minutes',
    cookTime: '10 minutes',
    difficulty: 'Easy',
    overview: 'Cloudflare Pages is a JAMstack platform for frontend developers to collaborate and deploy websites. Connect your Git repository and Pages will automatically build and deploy your site to Cloudflare\'s global network.',
    yield: '1 deployed website',
    moduleId: 'jamstack-deployment',
    ingredients: [
      {
        id: 'ing-5',
        name: 'GitHub/GitLab Account',
        description: 'Repository with your React app',
        required: true,
      },
      {
        id: 'ing-6',
        name: 'Cloudflare Account',
        description: 'Free account with Pages enabled',
        required: true,
      },
      {
        id: 'ing-7',
        name: 'React Application',
        description: 'Working React app ready to deploy',
        required: true,
      },
    ],
    steps: [
      {
        id: 'step-7',
        number: 1,
        title: 'Connect Your Repository',
        description: 'In the Cloudflare dashboard, navigate to Pages and click "Create a project". Connect your GitHub or GitLab account and select your React repository. Grant only the necessary repository permissions. You can connect multiple repositories later.',
      },
      {
        id: 'step-8',
        number: 2,
        title: 'Configure Build Settings',
        description: 'Set the build command to "npm run build" and the output directory to "build" or "dist" depending on your setup. Pages will auto-detect React projects. Verify your package.json has the correct build script. Add environment variables if needed.',
      },
      {
        id: 'step-9',
        number: 3,
        title: 'Deploy and Monitor',
        description: 'Click "Save and Deploy". Pages will build your site and deploy it to a unique URL. Monitor the build logs for any errors. First builds may take a few minutes. Check build logs if deployment fails. Your site gets a preview URL immediately.',
      },
    ],
    rating: 4.9,
    ratingCount: 697,
    comments: [
      {
        id: 'comment-4',
        author: 'Alex Kumar',
        date: '2024-01-12',
        rating: 5,
        text: 'Deployed my portfolio site in minutes! The automatic builds from Git are a game changer.',
        helpful: 31,
      },
    ],
  },
  {
    id: 'r2-storage',
    title: 'Object Storage with Cloudflare R2',
    author: 'Ali Slagle',
    videoUrl: 'https://customer-rhnwzxvb3mg4wz3.cloudflarestream.com/d5d1b4f3f8e6f8e6f8e6f8e6f8e6f8e6/manifest/video.m3u8',
    videoPoster: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=1200&h=600&fit=crop',
    description: 'Store and retrieve objects using Cloudflare R2, an S3-compatible storage solution with zero egress fees.',
    totalTime: '25 minutes',
    prepTime: '10 minutes',
    cookTime: '15 minutes',
    difficulty: 'Intermediate',
    overview: 'Cloudflare R2 Storage allows developers to store large amounts of unstructured data without the costly egress bandwidth fees associated with typical cloud storage services.',
    yield: '1 configured R2 bucket',
    moduleId: 'storage-solutions',
    ingredients: [
      {
        id: 'ing-8',
        name: 'Cloudflare Account',
        description: 'Account with R2 enabled',
        required: true,
      },
      {
        id: 'ing-9',
        name: 'AWS SDK or S3 Client',
        description: 'For programmatic access',
        required: true,
      },
      {
        id: 'ing-10',
        name: 'API Tokens',
        description: 'R2 access credentials',
        required: true,
      },
    ],
    steps: [
      {
        id: 'step-11',
        number: 1,
        title: 'Create an R2 Bucket',
        description: 'Navigate to R2 in your Cloudflare dashboard and create a new bucket. Choose a unique name and select your preferred location. Bucket names must be globally unique. Choose a location close to your users.',
      },
      {
        id: 'step-12',
        number: 2,
        title: 'Generate API Tokens',
        description: 'Create R2 API tokens with appropriate permissions. You\'ll need the Access Key ID and Secret Access Key for authentication. Store credentials securely. Use separate tokens for development and production.',
      },
      {
        id: 'step-13',
        number: 3,
        title: 'Configure Your Application',
        description: 'Install the AWS SDK and configure it to use R2 endpoints. Set the endpoint URL to your account\'s R2 endpoint. R2 is S3-compatible. Use environment variables for credentials.',
      },
    ],
    rating: 4.7,
    ratingCount: 2330,
    comments: [
      {
        id: 'comment-5',
        author: 'Jordan Lee',
        date: '2024-01-09',
        rating: 5,
        text: 'Finally switched from S3 to R2. The zero egress fees are saving us thousands per month!',
        helpful: 42,
      },
    ],
  },
  {
    id: 'workers-kv',
    title: 'Key-Value Storage with Workers KV',
    author: 'Eric Kim',
    videoUrl: 'https://customer-rhnwzxvb3mg4wz3.cloudflarestream.com/d5d1b4f3f8e6f8e6f8e6f8e6f8e6f8e6/manifest/video.m3u8',
    videoPoster: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=1200&h=600&fit=crop',
    description: 'Build fast, globally distributed applications with Workers KV, a low-latency key-value data store.',
    totalTime: '30 minutes',
    prepTime: '10 minutes',
    cookTime: '20 minutes',
    difficulty: 'Easy',
    overview: 'Workers KV is a global, low-latency, key-value data store that allows you to store and retrieve data from Cloudflare\'s edge network.',
    yield: '1 KV namespace',
    moduleId: 'serverless-computing',
    ingredients: [
      {
        id: 'ing-11',
        name: 'Cloudflare Workers Account',
        description: 'Active Workers subscription',
        required: true,
      },
      {
        id: 'ing-12',
        name: 'Wrangler CLI',
        description: 'Latest version',
        required: true,
      },
    ],
    steps: [
      {
        id: 'step-15',
        number: 1,
        title: 'Create KV Namespace',
        description: 'Use Wrangler to create a new KV namespace: wrangler kv:namespace create "MY_KV". This creates a globally distributed key-value store.',
      },
      {
        id: 'step-16',
        number: 2,
        title: 'Bind to Worker',
        description: 'Add the KV namespace binding to your wrangler.toml configuration file. This allows your Worker to access the KV store.',
      },
      {
        id: 'step-17',
        number: 3,
        title: 'Read and Write Data',
        description: 'Use the KV API to store and retrieve data in your Worker code. Data is automatically replicated across Cloudflare\'s global network.',
      },
    ],
    rating: 4.6,
    ratingCount: 9393,
    comments: [],
  },
  {
    id: 'durable-objects',
    title: 'Real-Time Apps with Durable Objects',
    author: 'Hetty Lui McKinnon',
    videoUrl: 'https://customer-rhnwzxvb3mg4wz3.cloudflarestream.com/d5d1b4f3f8e6f8e6f8e6f8e6f8e6f8e6/manifest/video.m3u8',
    videoPoster: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&h=600&fit=crop',
    description: 'Build collaborative, real-time applications using Cloudflare Durable Objects for strongly consistent coordination.',
    totalTime: '45 minutes',
    prepTime: '15 minutes',
    cookTime: '30 minutes',
    difficulty: 'Advanced',
    overview: 'Durable Objects provide a way to coordinate state across multiple clients with strong consistency guarantees.',
    yield: '1 real-time application',
    moduleId: 'serverless-computing',
    ingredients: [
      {
        id: 'ing-13',
        name: 'Workers Paid Plan',
        description: 'Durable Objects require paid plan',
        required: true,
      },
      {
        id: 'ing-14',
        name: 'WebSocket Knowledge',
        description: 'Understanding of WebSocket protocol',
        required: true,
      },
    ],
    steps: [
      {
        id: 'step-18',
        number: 1,
        title: 'Define Durable Object Class',
        description: 'Create a class that extends DurableObject with your application logic. This class will handle state and coordination.',
      },
      {
        id: 'step-19',
        number: 2,
        title: 'Configure Bindings',
        description: 'Set up Durable Object bindings in your wrangler.toml to connect your Worker to the Durable Object class.',
      },
      {
        id: 'step-20',
        number: 3,
        title: 'Implement Real-Time Logic',
        description: 'Use WebSockets and the Durable Object API to build real-time features like chat, collaboration, or gaming.',
      },
    ],
    rating: 4.5,
    ratingCount: 5413,
    comments: [],
  },
];

export const moduleCollections: ModuleCollection[] = [
  {
    id: 'serverless-computing',
    title: 'Serverless Computing with Workers',
    description: 'Master Cloudflare Workers and build fast, scalable serverless applications at the edge.',
    tutorials: tutorials.filter(t => t.moduleId === 'serverless-computing'),
  },
  {
    id: 'jamstack-deployment',
    title: 'JAMstack Deployment with Pages',
    description: 'Deploy modern web applications with Cloudflare Pages and enjoy automatic builds and global distribution.',
    tutorials: tutorials.filter(t => t.moduleId === 'jamstack-deployment'),
  },
  {
    id: 'storage-solutions',
    title: 'Storage Solutions',
    description: 'Learn to use Cloudflare\'s storage products including R2 object storage and Workers KV.',
    tutorials: tutorials.filter(t => t.moduleId === 'storage-solutions'),
  },
];

export const featuredTutorial = tutorials.find(t => t.featured) || tutorials[0];
